service: projeto-arcca
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getPlacesReviews:
    handler: src/index.getPlacesReviews
    # events:
    #   - eventBridge:
    #     schedule: "* 10 * * *"
    #     input:
    #       addresses:
    #         - "R. Visc. de Pirajá, 595 - Ipanema, Rio de Janeiro - RJ, 22410-003" # Nema 595
    #         - "R. Cap. Salomão, 11 - Humaitá, Rio de Janeiro - RJ, 22271-040" # Nema Humaita
    #         - "Av. Ataulfo de Paiva, 1120 - loja c - Leblon, Rio de Janeiro - RJ, 22440-035" # Nema Leblon
    environment:
      GOOGLE_API_KEY: ${env:GOOGLE_API_KEY}

  saveReviews:
    handler: src/index.saveReviews
    # events:
    #   - sqs:
    #     arn: # TODO
    #     batchSize: 100
